#Configuration for the plugin
####################################Database
Database:
  Host: 'jdbc:mysql://localhost:3306/example'
  User: 'Bob'
  Pass: 'Cake'
#####################################Messages
Messages:
  MessagePrefix: '$b[CN]&f '
  